openapi: 3.0.1
info:
  title: Local Energy Market Operator API
  version: "1.0"
servers:
- url: /
paths:
  /auth:
    post:
      tags:
      - Auth
      summary: Authorize a user and generate an auth token.
      description: Authorize a user.
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/AuthRequest'
        required: false
      responses:
        200:
          description: User authorized successfully.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/AuthResponse'
        403:
          description: Unauthorized.
          content: {}
        500:
          description: Backend error.
          content: {}
  /bids:
    post:
      tags:
      - Bids
      summary: Creates a new bid in the market. This is a request for Gen Tokens or
        Load Tokens.
      description: Create a new bid
      parameters:
      - name: transactionId
        in: query
        required: true
        schema:
          type: string
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/BidOrOfferRequest'
        required: false
      responses:
        201:
          description: Bid created successfully.
          content: {}
        403:
          description: Unauthorized.
          content: {}
        500:
          description: Backend error.
          content: {}
      security:
      - Bearer: []
  /offers:
    post:
      tags:
      - Offers
      summary: Creates a new token offer for either Gen Tokens or Load tokens.
      description: Create a new offer
      parameters:
      - name: transactionId
        in: query
        description: Transaction ID
        required: true
        schema:
          type: string
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/BidOrOfferRequest'
        required: false
      responses:
        201:
          description: Offer created successfully.
          content: {}
        403:
          description: Unauthorized.
          content: {}
        500:
          description: Backend error.
          content: {}
      security:
      - Bearer: []
  /transactions/{transactionId}:
    put:
      tags:
      - Transactions
      summary: Updates the status of an existing transaction.
      description: Update an existing transaction.
      parameters:
      - name: transactionId
        in: path
        description: Transaction ID
        required: true
        schema:
          type: string
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/TransactionStatusRequest'
        required: false
      responses:
        204:
          description: Transaction modified.
          content: {}
        403:
          description: Unauthorized.
          content: {}
        500:
          description: Backend error.
          content: {}
      security:
      - Bearer: []
  /users/{userId}/settlement:
    post:
      tags:
      - Settlement
      summary: Submit burnt tokens to receive remit in FIAT.
      description: Submit burnt tokens for remit.
      parameters:
      - name: userId
        in: path
        description: User ID
        required: true
        schema:
          type: string
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/SettlementRequest'
        required: false
      responses:
        200:
          description: Settlement successful.
          content: {}
        403:
          description: Unauthorized.
          content: {}
        500:
          description: Backend error.
          content: {}
      security:
      - Bearer: []
  /assets:
    get:
      tags:
      - Assets
      summary: Retrieve assets (FIAT or GEN/LOAD Tokens) that have been issued as
        a result of a matched bid or offer.
      description: Retrieve assets (FIAT or GEN/LOAD Tokens) that have been issued
        as a result of a matched bid or offer.
      parameters:
      - name: transactionId
        in: query
        description: Transaction ID for the bid or offer.
        required: true
        schema:
          type: string
      responses:
        200:
          description: Retrieved assets successfully.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/AssetResponse'
        403:
          description: Unauthorized.
          content: {}
        500:
          description: Backend error.
          content: {}
      security:
      - Bearer: []
components:
  schemas:
    AuthRequest:
      type: object
      properties:
        username:
          type: string
          description: Username.
        password:
          type: string
          description: Password.
    AuthResponse:
      type: object
      properties:
        authToken:
          type: string
          description: Authorization Token.
    BidOrOfferRequest:
      type: object
      properties:
        tokenType:
          type: string
          description: Type of token being requested. "GEN" or "LOAD".
          enum:
          - GEN
          - LOAD
        quantity:
          type: integer
          description: Token amount.
        unitPrices:
          type: array
          description: Price array for tokens. Array size should match the number
            of tokens being requested, and show individual prices for each token.
          items:
            type: number
        timeTicker:
          type: string
          description: The identifier for the timeslot in the market. This is a datetime
            string that corresponds to the ticker in the market exchange.
        assets:
          type: array
          description: Array of hashes for FIAT being used to make a bid or GEN/LOAD
            Tokens being put on offer.
          items:
            type: string
    SettlementRequest:
      type: object
      properties:
        assets:
          type: array
          description: Array of hashes for burnt tokens.
          items:
            type: string
    AssetResponse:
      type: object
      properties:
        assets:
          type: array
          description: Array of hashes FIAT or tokens that have been issued.
          items:
            type: string
    TransactionStatusRequest:
      type: object
      properties:
        status:
          type: string
          description: Status of the transaction to be updated.
          enum:
          - PENDING
          - MATCHED
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
